### ISSUE TITLE
What determines the URL of the uploaded skin?

### ISSUE THREAD

**Issue by tryashtar** [hawezo/MojangSharp#5] opened 2017-08-31 04:42 UTC
First of all, thank you so much for making this. It makes my life far easier when trying to interact with the API.
I have a bit of a question. I'm attempting to create a program that, while being used, changes the user's skin a few times, and it very specifically needs the `minecraft.net` URL that contains the new skin.
Currently, I have to submit a skin change request, then a profile request to get its `Properties.SkinUri`. However, requesting profiles is more heavily rate-limited according to http://wiki.vg/Mojang_API, and I've noticed that it is indeed quite slow.
Some experimentation led me to discover that uploading two identical skins produced the same URL, so that led me to assume one of two situations is happening:
* The server searches every uploaded skin looking for a copy and sets your skin to that URL to prevent duplicates (seems very slow and wasteful)
* Some sort of hash is generated from the image that determines the URL to resolve duplicates (seems likely).

If the latter is true, there must be a way to find the destination URL of a source skin *without* having to ask the API where it was placed. Do you know how this can be done?
Thanks again.

**Comment by innocenzi** [comment] 2017-08-31 07:57
Simple curiosity - what are you trying to achieve with changing a skin that often? 

Concerning the answer, I am pretty sure that they use your second method. Even locally, they use hashes to locate files, natives and stuff, there is no way they perform a full search on their skin database.

I think that, like you said, the uploaded skin is being used to generate a hash. The issue is that this hash probably contains salt, and thus, it is harder to find its source. This hash can also be generated thanks to a key unique to their servers.

In case where there is no salt nor password nor UUID from their servers, this is what you can search:
- UUID by file (PHP)
- File hash algorithms
- base64

You can exclude PHP's `hash_file()` since this code:
```php
foreach (hash_algos() as $hash) {
    echo hash_file($hash, "test.png");
    echo '<br/>';
}
```
Gave me numerous hashes which were not the good ones. The hash we're searching can be a hash based on the result of one of theses hashes, though.

TBH, it kind of looks like SHA-256 to me. Given the string length I mean. Maybe it contains salt, or it is hashed multiple times. Maybe it's Base64 or HEX.

... I'm not sure about what can I do to help you more, but without asking the API I don't know the exact method for getting the skin URL.

**Comment by innocenzi** [comment] 2017-08-31 11:13
If you're motivated you can perform tests there:
- https://md5hashing.net
- https://www.pelock.com/products/hash-calculator

Remember you'll probably have to hash and re-hash or something like this. Good luck, I don't know how to help more.

**Comment by tryashtar** [comment] 2017-09-03 04:17
Basically this is for a [program that generates player statues](https://github.com/tryashtar/yorick). The master player skin is broken up into 26 4x4x4 cubes, each of which need a skull and a skin, so I'm ultimately sending 27 skin change requests (pretty quick) and 27 profile requests (yikes!)

I poked around with those various hash sites (thank you, by the way), but got pretty demotivated. Unless I can get in contact with someone at Mojang who knows that information, it's not looking very promising for me. If I ever get it figured out, I'll let you know. Maybe you want to implement it as some sort of "artificial" skin upload response.

**Comment by innocenzi** [comment] 2017-09-03 09:10
I believe you can indeed try to contact someone at Mojang. I think it's your best bet, since the probability to find the good hash is really, really slow.

Let me know if somehow you can achieve to get the hash so I can emplement it. Good luck in your project.

I won't close this issue until we get a fix for that.

**Comment by tryashtar** [comment] 2017-09-06 15:57
I have been informed that the hashing algorithm used is HMAC-SHA1. After some basic research, I learned that this algorithm uses a secret key, which was not provided to me and likely will not be.

**Comment by innocenzi** [comment] 2017-09-06 16:46
Well, at least we have an hint. If you can contact them, you can maybe ask for them to publish an API especially for that (getting the skin URI) but I'd not expect that much from that approach.

Maybe the secret is an obvious string based of Mojang/Minecraft related words.

If you want to perform tests, you can try there: 
<old_url>hash.php?key= (key is the secret)
If you use this, you'll have to find what gives this hash: ` 1551f39134e19783b42c7c31f6077a87c8793ed45e9967932119cb24c3cb1`.
If you can find, you got the key. Let's just hope this is a static secret and not a dynamic one.

**EDIT** ─ Your best bet is hashcat.
**EDIT** ─ Removed the URL.

**Closed as completed** 2019-04-09 15:26 UTC
Labels: help wanted, wontfix, waiting for op
